"""add roster year

Revision ID: 3f44d0596d73
Revises: 296e9cfdb196
Create Date: 2017-08-19 20:41:16.245807

"""

# revision identifiers, used by Alembic.
revision = '3f44d0596d73'
down_revision = '296e9cfdb196'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('year', sa.String(length=25), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'year')
    ### end Alembic commands ###
